import type { LucideProps } from 'lucide-react'
import {
  Activity,
  AlertCircle,
  ArrowRight,
  ArrowUpRight,
  BellRing,
  Bookmark,
  Box,
  Check,
  ChevronRight,
  CircleDot,
  Clock,
  Compass,
  Flame,
  Heart,
  Home,
  LayoutGrid,
  ListChecks,
  Map,
  MapPin,
  MoreHorizontal,
  Navigation,
  Package,
  Pause,
  Play,
  Plus,
  Power,
  RefreshCw,
  Route,
  Search,
  Settings,
  ShoppingBag,
  Sparkles,
  Star,
  Store,
  Target,
  TrendingUp,
  Trophy,
  Wallet,
  Wifi,
  WifiOff,
  X,
  Zap,
} from 'lucide-react'

const baseProps: Partial<LucideProps> = {
  strokeWidth: 1.8,
  absoluteStrokeWidth: false,
}

export const Icon = {
  Activity: (p: LucideProps) => <Activity {...baseProps} {...p} />,
  AlertCircle: (p: LucideProps) => <AlertCircle {...baseProps} {...p} />,
  ArrowRight: (p: LucideProps) => <ArrowRight {...baseProps} {...p} />,
  ArrowUpRight: (p: LucideProps) => <ArrowUpRight {...baseProps} {...p} />,
  BellRing: (p: LucideProps) => <BellRing {...baseProps} {...p} />,
  Bookmark: (p: LucideProps) => <Bookmark {...baseProps} {...p} />,
  Box: (p: LucideProps) => <Box {...baseProps} {...p} />,
  Check: (p: LucideProps) => <Check {...baseProps} {...p} />,
  ChevronRight: (p: LucideProps) => <ChevronRight {...baseProps} {...p} />,
  CircleDot: (p: LucideProps) => <CircleDot {...baseProps} {...p} />,
  Clock: (p: LucideProps) => <Clock {...baseProps} {...p} />,
  Compass: (p: LucideProps) => <Compass {...baseProps} {...p} />,
  Flame: (p: LucideProps) => <Flame {...baseProps} {...p} />,
  Heart: (p: LucideProps) => <Heart {...baseProps} {...p} />,
  Home: (p: LucideProps) => <Home {...baseProps} {...p} />,
  LayoutGrid: (p: LucideProps) => <LayoutGrid {...baseProps} {...p} />,
  ListChecks: (p: LucideProps) => <ListChecks {...baseProps} {...p} />,
  Map: (p: LucideProps) => <Map {...baseProps} {...p} />,
  MapPin: (p: LucideProps) => <MapPin {...baseProps} {...p} />,
  More: (p: LucideProps) => <MoreHorizontal {...baseProps} {...p} />,
  Navigation: (p: LucideProps) => <Navigation {...baseProps} {...p} />,
  Package: (p: LucideProps) => <Package {...baseProps} {...p} />,
  Pause: (p: LucideProps) => <Pause {...baseProps} {...p} />,
  Play: (p: LucideProps) => <Play {...baseProps} {...p} />,
  Plus: (p: LucideProps) => <Plus {...baseProps} {...p} />,
  Power: (p: LucideProps) => <Power {...baseProps} {...p} />,
  RefreshCw: (p: LucideProps) => <RefreshCw {...baseProps} {...p} />,
  Route: (p: LucideProps) => <Route {...baseProps} {...p} />,
  Search: (p: LucideProps) => <Search {...baseProps} {...p} />,
  Settings: (p: LucideProps) => <Settings {...baseProps} {...p} />,
  ShoppingBag: (p: LucideProps) => <ShoppingBag {...baseProps} {...p} />,
  Sparkles: (p: LucideProps) => <Sparkles {...baseProps} {...p} />,
  Star: (p: LucideProps) => <Star {...baseProps} {...p} />,
  Store: (p: LucideProps) => <Store {...baseProps} {...p} />,
  Target: (p: LucideProps) => <Target {...baseProps} {...p} />,
  TrendingUp: (p: LucideProps) => <TrendingUp {...baseProps} {...p} />,
  Trophy: (p: LucideProps) => <Trophy {...baseProps} {...p} />,
  Wallet: (p: LucideProps) => <Wallet {...baseProps} {...p} />,
  Wifi: (p: LucideProps) => <Wifi {...baseProps} {...p} />,
  WifiOff: (p: LucideProps) => <WifiOff {...baseProps} {...p} />,
  X: (p: LucideProps) => <X {...baseProps} {...p} />,
  Zap: (p: LucideProps) => <Zap {...baseProps} {...p} />,
}
